### ISSUE TITLE
Merge mashDistOutputJson JSON files into one for each sample

### ISSUE THREAD

**Issue by ODiogoSilva** [tiagofilipe12/pATLAS#132]
Currently, patlasflow outputs a JSON for each contig in each sample. I suggest merging the individual contig JSONs into a single file, with a key:value pair for each contig:plasmids.

**Comment by tiagofilipe12** [comment]
This would require a refactor in patlas with two sliders for files. One to cycle between all the contigs of a file and another one currently implemented that enables to cycle between files.

**Comment by tiagofilipe12** [comment]
And a refactor of the process mentioned by @odiogosilva in patlasflow.
