### ISSUE TITLE
Implement log of additions and deletions from db

### ISSUE THREAD

**Issue by tiagofilipe12** [tiagofilipe12/pATLAS#156]
In the script `MASHix.py` we could implement a log of all the accession numbers in this next release and from there on we could start making diffs so that we can know easily what have been added or removed from pATLAS database (for each refseq update). Then, we could think of some nice way to publish these diffs.

**Comment by jacarrico** [comment]
We have to think where and how the diffs will be available from the Mashix output and how that will work out with the user databases and user driven updates in local copies.

**Comment by tiagofilipe12** [comment]
Now `MASHix.py` writes to a file the entries that will be added to each version of pATLAS, generated by this script as well. It only needs a diff between old version and the new one.

Regarding the way we display this diff, the simpler way would be to do a log of all the changes made to the database similarly to what is done in `changelog.md` for the code. But that is a rather poor visualization of what is subtracted or added to the database...

**Comment by tiagofilipe12** [comment]
Now, release 1.6.0 has a file with all the removed entries that can be used for the next database release in order to make a diff between the two releases in terms of removed sequences.

**Comment by tiagofilipe12** [comment]
Here is a figure describing all the links between plasmid sequences with more than 10k bp, comprising more than 200,000 links.
![newplot](https://user-images.githubusercontent.com/6191251/46065067-08503080-c169-11e8-85d9-4e48f0480d5d.png)

It can be observed that the vast majority of the links tend to be > 0.9 (1-mash dist) and > 0.9 ANI, which means that the overwhelming majority of the links would be the same as the ones available in pATLAS.
